site_name: Vampires Dawn Community Edition
repo_url: https://github.com/VampiresDawnCommunity/vdce-docs

use_directory_urls: false

nav:
  - Home: index.md
  - Changelog:
    - Allgemein: changelog/README.md
    - Vanilla: changelog/vanilla.md
    - Special Edition: changelog/special-edition.md
    - Aysha-Mod: changelog/aysha-integration.md
    - Everlasting Reign: changelog/everlasting-reign.md
    - Valaine-Mod: changelog/valaine-integration.md
    - div. Mods: changelog/mods-other.md
    - CE-Updates: changelog/changelog-ce.md
  - Developer Info:
    - EasyRPG: dev-info/easyrpg.md
    - Glossar: dev-info/glossary.md
    - Timeline: dev-info/timeline.md
  - Soundtrack: 
    - Vanilla: soundtrack/vanilla.md
    - Mods: soundtrack/mods.md

theme:
  name: material
 
#extra:
#  alternate:
#    - name: Deutsch
#      link: /de/
#      lang: de
#    - name: English
#      link: /en/
#      lang: en